### ISSUE TITLE
Have an option to run vtgates as a DaemonSet

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess-operator#9]
To reduce latency, if we can run vtgate as a DaemonSet, that first hop doesn't go over the network. This is an example of how linkerd does it.

```
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: http_proxy
          value: $(NODE_NAME):4140
```
https://linkerd.io/1/getting-started/k8s/
